InvestmentFront/Models/LoanInfo.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace InvestmentFront.Models
{
    public class LoanInfo
    {
        public int LoanID { get; set; }
    }
}

InvestmentFront/Models/LoanRequestInfo.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace InvestmentFront.Models
{
    public class LoanRequestInfo
    {
        public int LoanRequestID { get; set; }
    }
}

InvestmentFront/Models/LoanViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace InvestmentFront.Models
{
    public class LoanViewModel
    {
        public string AgreementNumber { get; set; }
        public double CreditAmount { get; set; }
        public double Amount { get; set; }
        public IEnumerable<ScheduleViewModel> Schedule { get; set; }
    }
}

InvestmentFront/Models/ProductInfo.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace InvestmentFront.Models
{
    public class ProductInfo
    {
        public ProductInfo() {
            Amounts = new List<SelectListItem>();
            Terms = new List<SelectListItem>();
        }

        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { set; get; }
        public decimal AnnualRate { get; set; }
        public decimal Amount { get; set; }
        public List<SelectListItem> Amounts { get; set; }
        public int Term { get; set; }
        public List<SelectListItem> Terms { get; set; }
        public decimal MinAmount { get; set; }
        public decimal MaxAmount { get; set; }
        public int AmountStep { get; set; }
        public int MinTerm { get; set; }
        public int MaxTerm { get; set; }
    }
}

InvestmentFront/Models/ScheduleViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace InvestmentFront.Models
{
    public class ScheduleViewModel
    {
        public int Id { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2}")]
        public double Payment { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2}")]
        public double Body { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2}")]
        public double Percent { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2}")]
        public double Left { get; set; }

        public DateTime PaymentDate { get; set; }
    }
}

InvestmentFront/Controllers/HomeController.cs
using AutoMapper;
using InvestmentFront.Domain.Abstraction;
using InvestmentFront.Domain.Entities;
using InvestmentFront.Infrastructure.Services;
using InvestmentFront.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace InvestmentFront.Controllers
{
    public class HomeController : Controller
    {
        public IRepository<Loan> _loanRepository { get; }
        public ICalculationService _calculator { get; }
        public IMapper _mapper { get; }

        public HomeController(IRepository<Loan> loanRepository, ICalculationService calculator, IMapper mapper) {
            _loanRepository = loanRepository;
            _calculator = calculator;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var loans = _loanRepository.GetAll();
            var schedules = new List<LoanViewModel>();
            foreach (var item in loans) {
                var schedule = _calculator.PaymentScheduleAnnuitet(item.Amount, item.Product.AnnualRate, item.Term * 12, item.AgreementDate);
                var loan = new LoanViewModel {
                    AgreementNumber = item.AgreementNumber,
                    CreditAmount = item.CurrentDebt,
                    Amount = item.Amount,
                    Schedule = _mapper.Map<IEnumerable<ScheduleViewModel>>(schedule)
                };
                schedules.Add(loan);
            }
            return View(schedules);
        }
    }
}

InvestmentFront/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InvestmentFront.Domain.Abstraction;
using InvestmentFront.Domain.Entities;
using InvestmentFront.Infrastructure.BUS;
using InvestmentFront.Models;
using Microsoft.AspNetCore.Mvc;

namespace InvestmentFront.Controllers
{
    public class LoanController : Controller
    {
        public IRepository<LoanRequest> _loanRequestRepository { get; }
        public ICommandBus _commandBus { get; }

        public LoanController(IRepository<LoanRequest> loanRequestRepository, ICommandBus commandBus) {
            _loanRequestRepository = loanRequestRepository;
            _commandBus = commandBus;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetLoans() {
            var requests = _loanRequestRepository.GetAll();
            return View("", requests);
        }

        [HttpPost]
        public IActionResult AddLoanRequest(ProductInfo request) {

            var result = _commandBus.Submit<LoanRequestCommand>(new LoanRequestCommand(request));
            if (result.Success) {
                return RedirectToAction("Index", "Home");
            }

            var requests = _loanRequestRepository.GetAll();
            return View("", requests);
        }
    }
}

InvestmentFront/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using InvestmentFront.Domain.Abstraction;
using InvestmentFront.Domain.Entities;
using InvestmentFront.Infrastructure.BusinessLogic;
using InvestmentFront.Infrastructure.Services;
using InvestmentFront.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InvestmentFront.Controllers
{
    public class ProductController : Controller
    {
        public IProductService _productService{ get; }

        public ProductController(IProductService productService) {
            _productService = productService;
        }

        [HttpGet]
        public IActionResult GetProducts() {
            var products = _productService.GetProducts();
            return View(products);
        }
    }
}

InvestmentFront/Views/Home/Index.cshtml
@model IEnumerable<LoanViewModel>

@{
    ViewData["Title"] = "Index";
}

    <div class="row">
        <div class="col-12">
            <table class="table table-sm table-striped table-hover border-bottom">
                <tbody>
                    @if (Model.Count() > 0) {
                        @foreach (var item in Model) {
                    <tr>
                        <td class="d-none d-lg-table-cell">
                            @Html.LabelFor(modelItem => item.AgreementNumber) :  @Html.DisplayFor(modelItem => item.AgreementNumber)
                            <br />
                            @Html.LabelFor(modelItem => item.CreditAmount) : @Html.DisplayFor(modelItem => item.CreditAmount)
                            <br />
                            @Html.LabelFor(modelItem => item.Amount) : @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-12">
                                    <table class="table table-sm table-striped table-hover border-bottom">
                                        <tbody>
                                                @foreach (var sch in item.Schedule) {
                                            <tr>
                                                <td class="d-none d-lg-table-cell">
                                                    @Html.DisplayFor(modelItem => sch.Id)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => sch.PaymentDate)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => sch.Payment)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => sch.Body)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => sch.Percent)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => sch.Left)
                                                </td>
                                            </tr>
                                                }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </td>

                    </tr>
                        }
                    } else {
                        <tr>
                            <td colspan="6" class="text-center">
                                No Food Found
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

InvestmentFront/Views/Product/GetProducts.cshtml
@using InvestmentFront.Models
@model IEnumerable<ProductInfo>

@{
    ViewData["Title"] = "List";
}

@foreach (var product in Model) {
    <partial name="ProductSummaryPartial" model="@product" />
}

InvestmentFront/Views/Product/ProductSummaryPartial.cshtml
@using InvestmentFront.Models
@model ProductInfo


<div class="card card-header-pills m-1 p-1">
    <div class="bg-light p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right;">
                <small>@Model.AnnualRate.ToString("c")</small>
                <small>@Model.Category</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductID" asp-action="AddLoanRequest" asp-controller="Loan" method="post">
        <input type="hidden" asp-for="ProductID" />
        @Html.LabelFor(x => x.Amounts)
        <label asp-for="Amount"></label>
        <select asp-for="Amount" asp-items="@Model.Amounts"></select>
        <label asp-for="Term"></label>
        <select asp-for="Term" asp-items="@Model.Terms"></select>
        <span class="card-text p-1">
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">
                GetLoan
            </button>
        </span>
    </form>
</div>

InvestmentFront/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SimCorp</title>
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/**/*.min.css" asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SimCorp", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Products", "GetProducts", "Product")</li>
                    <li>@Html.ActionLink("Investments", "Details", "Loan")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="panel-body">
            <div class="row">
                <br /><br />
            </div>
            <div class="row">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>